"use client";

import Link from "next/link";
import { FiArrowLeft, FiArrowRight } from "react-icons/fi";
import { useOnboarding, type OpeningHour } from "@/src/context/OnboardingContext";

const SERVICES = ["Outdoor Seating", "Private Dining Room", "Takeaway / Delivery", "Consultation", "Marketing", "SEO Optimization"];
export default function Configure() {
  const { formData, updateFormData, saveDraft } = useOnboarding();
  const toggleService = (service: string) => updateFormData({ services: formData.services.includes(service) ? formData.services.filter((item) => item !== service) : [...formData.services, service] });
  const updateHour = (day: string, patch: Partial<OpeningHour>) => updateFormData({ openingHours: formData.openingHours.map((hour) => hour.day === day ? { ...hour, ...patch } : hour) });
  return <div className="max-w-3xl"><section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-lg font-bold text-slate-900">Step 3: Business Details</h2><h3 className="mt-6 text-sm font-bold text-slate-900">Services Offered</h3><div className="mt-3 flex flex-wrap gap-2">{SERVICES.map((service) => <button key={service} type="button" onClick={() => toggleService(service)} className={`rounded-full border px-3 py-1.5 text-sm ${formData.services.includes(service) ? "border-[#00663f] bg-[#e4f3ec] text-[#00663f]" : "border-slate-200 text-slate-600"}`}>{service}</button>)}</div><h3 className="mt-7 text-sm font-bold text-slate-900">Opening Hours</h3><div className="mt-3 divide-y divide-slate-100">{formData.openingHours.map((hour) => <div key={hour.day} className="flex flex-wrap items-center gap-3 py-3"><span className="w-24 text-sm font-medium">{hour.day}</span><button type="button" onClick={() => updateHour(hour.day, { isClosed: !hour.isClosed })} className={`rounded-full px-3 py-1 text-xs font-semibold ${hour.isClosed ? "bg-slate-100 text-slate-400" : "bg-[#e4f3ec] text-[#00663f]"}`}>{hour.isClosed ? "Closed" : "Open"}</button><input type="time" disabled={hour.isClosed} value={hour.open} onChange={(e) => updateHour(hour.day, { open: e.target.value })} className="rounded border border-slate-200 px-2 py-1 text-sm disabled:bg-slate-50" /><span>-</span><input type="time" disabled={hour.isClosed} value={hour.close} onChange={(e) => updateHour(hour.day, { close: e.target.value })} className="rounded border border-slate-200 px-2 py-1 text-sm disabled:bg-slate-50" /></div>)}</div><div className="mt-6 flex justify-between border-t border-slate-100 pt-5"><div className="flex gap-4"><Link href="/onboarding/contact" className="flex items-center gap-2 text-sm font-semibold text-slate-500"><FiArrowLeft />Back</Link><button type="button" onClick={saveDraft} className="text-sm font-semibold text-slate-500">Save Draft</button></div><Link href="/onboarding/showCase" className="flex items-center gap-2 rounded-xl bg-[#00663f] px-5 py-2.5 text-sm font-semibold text-white">Continue <FiArrowRight /></Link></div></section></div>;
}
